version: "2"
plugins:
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php
      rulesets: "unusedcode,naming,design,codesize"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions:
        - php
      standard: "PSR1,PSR2"
      ignore_warnings: true
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
exclude_paths:
  - "node_modules/"
  - "vendor/"
  - "bootstrap/"
  - "database/"
  - "public/"
  - "storages/"
  - "tests/"
